### ISSUE TITLE
CodeChecker does not work with stock ubuntu 18.04 clang 6 (ccache)

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#2730]
./build/CodeChecker/bin/CodeChecker
Traceback (most recent call last):
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 108, in main
    subcommands[subcommand])
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 44, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/analyze.py", line 418, in add_arguments_to_parser
    if analyzer_types.is_ctu_capable(context):
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/analyzer_types.py", line 36, in is_ctu_capable
    clangsa_cfg = ClangSA.construct_config_handler([], context)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 357, in construct_config_handler
    checkers = ClangSA.get_analyzer_checkers(handler, environ)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 105, in get_analyzer_checkers
    alpha=True)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/clang_options.py", line 37, in get_analyzer_checkers_cmd
    if cfg_handler.version_info.vendor != "clang":
AttributeError: 'bool' object has no attribute 'vendor'

(venv_dev) ednikru@kojak:/mnt/ssd/ednikru/codechecker$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by VladAdGad** [comment]
It is definitely relate with ccache. I have the same problem with ubuntu20.04. It complains about clang but I want to output just a "help" :) CodeChecker [ANY COMMAND HERE] outputs same error as above. When I remove ccache everything is work

**Comment by VladAdGad** [comment]
@dkrupp https://github.com/Ericsson/codechecker/issues/3117#issuecomment-752624043
