### PR TITLE
[analyzer] Handle wrong clang version

### LINKED ISSUE #2730: CodeChecker does not work with stock ubuntu 18.04 clang 6 (ccache)
./build/CodeChecker/bin/CodeChecker
Traceback (most recent call last):
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 108, in main
    subcommands[subcommand])
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 44, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/analyze.py", line 418, in add_arguments_to_parser
    if analyzer_types.is_ctu_capable(context):
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/analyzer_types.py", line 36, in is_ctu_capable
    clangsa_cfg = ClangSA.construct_config_handler([], context)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 357, in construct_config_handler
    checkers = ClangSA.get_analyzer_checkers(handler, environ)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/analyzer.py", line 105, in get_analyzer_checkers
    alpha=True)
  File "/mnt/ssd/ednikru/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzers/clangsa/clang_options.py", line 37, in get_analyzer_checkers_cmd
    if cfg_handler.version_info.vendor != "clang":
AttributeError: 'bool' object has no attribute 'vendor'

(venv_dev) ednikru@kojak:/mnt/ssd/ednikru/codechecker$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #2730

If clang was a symlink for example to ccache we tried to get the version
information of this binary. CodeChecker threw an exception in this case.
This commit will handle this use case properly.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5511976&bid=18063755)

**Comment by csordasmarton** [comment]
@gyorb This is also handled by this commit. `CodeChecker --help` command just show me the help message without exception.

File: analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py [hunk 1]
```diff
@@ -22,6 +22,10 @@ def get_analyzer_checkers_cmd(cfg_handler, alpha=True, debug=True):
     Before clang9 alpha and debug checkers were printed by default.
     Since clang9 there are extra arguments to print the additional checkers.
     """
+    if not cfg_handler.version_info:
+        LOG.debug("No clang version information. Can not get checkers.")
```
Comment (whisperity) [inline analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py:26]: This should be a warning, not a normally silent debug.

**Comment by dkrupp** [comment]
I don't like this solution. 
clang being a symlink to ccache is a common setup use case that should be handled.

Since  calling /usr/lib/ccache/clang works from the command line, it CodeChecker should be able to invoke it also. Swallowing the version detection error silently is also not so nice.

/usr/lib/ccache/clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
iIt should w

**Comment by kenroser** [comment]
I'm another user who couldn't figure out why CodeChecker crashed.  It started working with I took ccache out of my PATH.

**Comment by bruntib** [comment]
Implemented by #3204.
